### ISSUE TITLE
Lab Report 4 Feedback

### ISSUE THREAD

**Issue by JIzabal** [tiarahe2002/cse15l-lab-reports#5]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
  - Missing a url in the expected output of `testSnip2`. Use [the CommonMark demo site](https://spec.commonmark.org/dingus/) to see what output you're missing
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:

Feel free to comment below any questions about the rubric/feedback
Show the output of running the tests after updating with the correct output

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by JIzabal** [comment]
Your current expected output for snippet 2 shouldn't have `b.com`. Use [the CommonMark demo site](https://spec.commonmark.org/dingus/?text=%5Ba%20%5Bnested%20link%5D(a.com)%5D(b.com)%0A%0A%5Ba%20nested%20parenthesized%20url%5D(a.com(()))%0A%0A%5Bsome%20escaped%20%5C%5B%20brackets%20%5C%5D%5D(example.com)) to see what output you're missing. The highlighted links should be what you have in your expected output. Once you fix this, respond here so I can check.

**Comment by junlinchen12138** [comment]
Thank you for your time. I updata the issues!

**Comment by tiarahe2002** [comment]
Thank you for your time. I updated the issues.

**Comment by JIzabal** [comment]
Nice work!
